global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['127.0.0.1:9090', '192.168.206.128:9100']
        labels:
          group: 'prometheus'

rule_files:
  - "/etc/prometheus/prometheus_*_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.206.128:9093']
